# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density of Dirichlet-Multinomial Distribution
#' 
#' @description Computes the density of a Dirichlet-Multinomial (DM) distribution, at a given 
#' count vector \code{x}, with a user-specified prior count vector \code{prior}. 
#' 
#' @param x the count vector at which to evaluate the DM density 
#' @param prior the prior count vector, must have \code{length = length(x)}
#' @param log_form whether to return the log-density, default = TRUE
#' @param normalize whether to normalize the calculated density by \code{sum(x)}. 
#' Default = TRUE. 
#' 
#' @return The evaluated DM density (a number)
#' 
#' @export
dDirMult <- function(x, prior, log_form = TRUE, normalize = TRUE) {
    .Call(`_TopoRNet_dDirMult`, x, prior, log_form, normalize)
}

#' Topographic Product of a TRN
#' 
#' @description The Topographic Product of a TRN which is imbued with an output topology.  
#' 
#' @param input_coords the coordinates of the vertices in the Input space (i.e, R^d) of the TRN
#' @param output_coords the coordinates of the vertices in the Output space of the TRN 
#' @param parallel, whether to compute in parallel. Default = T.
#' 
#' @return The Topographic Product (a number)
#' 
#' @references 
#' \insertRef{BauerPawelzikGeisel1992}{TopoRNet}
#' @export
Topographic_Product <- function(input_coords, output_coords, parallel = TRUE) {
    .Call(`_TopoRNet_Topographic_Product`, input_coords, output_coords, parallel)
}

#' Topographic Functions of a TRN 
#' 
#' @description The Topograph Functions of a TRN measure topology preservation across a range of "folding" lengths, 
#' which are defined as the length (geodesic distance) by which edges in one space (input / output) must "fold" in order 
#' to be represented in the other.  
#' 
#' The functions computed here are the TF (Topographic Function) of Villmann et al. and the 
#' DTF (Differential Topographic Function ) & WDTF (Weighted DTF) of Zhang et al. 
#' 
#' @param inputADJ the adjacency matrix of vertices in the Input space of the TRN 
#' @param outputADJ the adjacency matrix of vertices in the Output sapce of the TRN 
#' @param parallel, whether to compute in parallel. Default = T. 
#' 
#' @return a data frame with columns: 
#' \itemize{
#' \item \code{k} list of folding lengths
#' \item \code{TF} the TF computed at each folding length 
#' \item \code{DTF} the DTF computed at each folding length 
#' \item \code{WDTF} the WDTF computed at each folding length 
#' }
#' 
#' \insertRef{VillmannDerHerrmannMartinetz1997}{TopoRNet}
#' \insertRef{ZhangMerenyi2006}{TopoRNet}
#' @export
Topographic_Functions <- function(inputADJ, outputADJ, parallel = TRUE) {
    .Call(`_TopoRNet_Topographic_Functions`, inputADJ, outputADJ, parallel)
}

